### ISSUE TITLE
Multiadmin in the latest version does not work in Tcadmin Panel

### ISSUE THREAD

**Issue by SrLicht** [ServerMod/MultiAdmin#254]
When trying to start the server it constantly gives this error

```cmd
[15:54:34] Starting this instance with config directory: "configuracion-del-servidor"...
[15:54:34] Using global config "scp_multiadmin.cfg"...
[15:54:34] Using server config "configuracion-del-servidor\scp_multiadmin.cfg"...
[15:54:34] Executing "SCPSL.exe"...
[15:54:34] Starting server with the following parameters:
SCPSL.exe -multiadmin:3.4.0.0:1 -batchmode -nographics -silent-crashes -nodedicateddelete -id15744 -console61715 -port7777 -logFile logs\2021-02-01_15_54_34_SCP_log_7777.txt -sharenonconfigs -configpath configuracion-del-servidor -appdatapath configuracion-del-servidor
[15:54:34] MultiAdmin v3.4.0.0 (https://github.com/ServerMod/MultiAdmin/)
Released under MIT License Copyright c Grover 2021
Unhandled Exception: System.InvalidOperationException: Cannot see if a key has been pressed when either application does not have a console or when console input has been redirected from a file. Try Console.In.Peek.
   at System.Console.get_KeyAvailable()
   at MultiAdmin.ServerIO.InputHandler.<WaitForKey>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MultiAdmin.ServerIO.InputHandler.<GetInputLineOld>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MultiAdmin.ServerIO.InputHandler.<Write>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   ```
   
   
![image](https://user-images.githubusercontent.com/36207738/106505204-b93c0800-64a6-11eb-8b21-065be7a1a3d4.png)

**Comment by SrLicht** [comment]
I don't know whether to create another Issue, so I'll put it here, I've had a problem for a long time that once a day the server freezes and does not write to the console again, it doesn't let the players enter and I have FastRound disabled and the Idle too.
I have tried to see the console when this happens at the moment I do not have older logs since they are deleted alone by the panel that I use, what if this file is created every time it happens
[2021-02-24_03_54_MA_3.3.1.1_debug_log.txt](https://github.com/ServerMod/MultiAdmin/files/6034118/2021-02-24_03_54_MA_3.3.1.1_debug_log.txt)

**Comment by Dankrushen** [comment]
As of MultiAdmin v3.4.0.1 you should be able to use `console_input_system: Original` as a workaround for this issue.
